Add tests for signed debug apk

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -8,26 +8,22 @@ app:
   - GRADLEW_PATH: "./gradlew"
 
   # define these in your .bitrise.secrets.yml
-  - BITRISEIO_ANDROID_KEYSTORE_URL: $BITRISEIO_ANDROID_KEYSTORE_URL
-  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_ALIAS: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
-  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_1_URL: $BITRISEIO_ANDROID_KEYSTORE_URL
-  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_1: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_1: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
-  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_1: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_2_URL: $BITRISEIO_ANDROID_KEYSTORE_URL
-  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_2: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_2: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
-  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_2: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_3_URL: $BITRISEIO_ANDROID_KEYSTORE_URL
-  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_3: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_3: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
-  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_3: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_4_URL: $BITRISEIO_ANDROID_KEYSTORE_URL
-  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD
-  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_4: $BITRISEIO_ANDROID_KEYSTORE_ALIAS
-  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD
+  - BITRISEIO_ANDROID_KEYSTORE_1_URL: $BITRISEIO_ANDROID_KEYSTORE_1_URL
+  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_1: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_1
+  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_1: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_1
+  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_1: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_1
+  - BITRISEIO_ANDROID_KEYSTORE_2_URL: $BITRISEIO_ANDROID_KEYSTORE_2_URL
+  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_2: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_2
+  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_2: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_2
+  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_2: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_2
+  - BITRISEIO_ANDROID_KEYSTORE_3_URL: $BITRISEIO_ANDROID_KEYSTORE_3_URL
+  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_3: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_3
+  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_3: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_3
+  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_3: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_3
+  - BITRISEIO_ANDROID_KEYSTORE_4_URL: $BITRISEIO_ANDROID_KEYSTORE_4_URL
+  - BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4
+  - BITRISEIO_ANDROID_KEYSTORE_ALIAS_4: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
+  - BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
 
 workflows:
   # ----------------------------------------------------------------
@@ -42,6 +38,7 @@ workflows:
     - go-test:
     after_run:
     - test_apk
+    - test_apk_debug
     - test_bundle
 
   test_apk:
@@ -50,7 +47,18 @@ workflows:
     - APK_FILE_INCLUDE_FILTER: "*.apk"
     after_run:
     - create_build_artifact
-    - test
+    - _jarsigner
+    - _apksigner
+
+  # Using apksigner zipalign fails to zipalign already zipaligned artifact
+  test_apk_debug:
+    envs:
+    - GRADLE_TASK: assembleDebug
+    - APK_FILE_INCLUDE_FILTER: "*.apk"
+    after_run:
+    - create_build_artifact
+    - _jarsigner
+    - _apksigner
     
   test_bundle:
     envs:
@@ -58,14 +66,15 @@ workflows:
     - APK_FILE_INCLUDE_FILTER: "*.aab"
     after_run:
     - create_build_artifact
-    - test
+    - _jarsigner
+    - _apksigner
 
   create_build_artifact:
     steps:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
             rm -rf ./_tmp
     - change-workdir:
@@ -96,44 +105,97 @@ workflows:
         inputs:
         - ndk_revision: '16'
         run_if: ".IsCI"
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            envman unset --key BITRISE_APK_PATH
+            envman unset --key BITRISE_AAB_PATH
     - gradle-runner:
         inputs:
         - gradle_task: "$GRADLE_TASK"
         - gradlew_path: "$GRADLEW_PATH"
         - app_file_include_filter: $APK_FILE_INCLUDE_FILTER
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            if [ -n "$BITRISE_APK_PATH" ]; then
+              envman add --key ORIG_BITRISE_APK_PATH --value ${BITRISE_APK_PATH}
+            fi
 
-  test:
+  reset_apk_path:
     steps:
-    # - path::./:
-    #     title: Step Test - keystore pass == key pass with Jar signer
-    #     inputs:
-    #     - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_1_URL
-    #     - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_1
-    #     - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_1
-    #     - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_1
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            set -ex
+            if [ -n "$ORIG_BITRISE_APK_PATH" ]; then
+              envman add --key BITRISE_APK_PATH --value ${ORIG_BITRISE_APK_PATH}
+            fi
+
+  _jarsigner:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            echo "jarsigner"
+            envman add --key APK_SIGNER --value "false"
+    after_run:
+    - _tests
+
+  _apksigner:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            echo "apksigner"
+            envman add --key APK_SIGNER --value "true"
+    after_run:
+    - _tests
+
+  _tests:
+    after_run:
+    - reset_apk_path
+    - test1
+    - reset_apk_path
+    - test2
+    - reset_apk_path
+    - test3
+    - reset_apk_path
+    - test4
+    - reset_apk_path
+    - test5
+    - reset_apk_path
+    - test6
+
+  test1:
+    steps:
     - path::./:
-        title: Step Test - keystore pass == key pass with APK signer
+        title: Step Test - keystore pass == key pass
         inputs:
         - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_1_URL
         - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_1
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_1
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_1
-        - use_apk_signer: true
+        - use_apk_signer: $APK_SIGNER
+
+  test2:
+    steps:
     - path::./:
-        title: Step Test - keystore pass != key pass with Jar signer
+        title: Step Test - keystore pass != key pass
         inputs:
         - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_2_URL
         - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_2
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_2
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_2
-    - path::./:
-        title: Step Test - keystore pass != key pass with APK signer
-        inputs:
-        - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_2_URL
-        - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_2
-        - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_2
-        - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_2
-        - use_apk_signer: true
+        - use_apk_signer: $APK_SIGNER
+
+  test3:
+    steps:
     - path::./:
         title: Step Test - default alias
         inputs:
@@ -141,14 +203,10 @@ workflows:
         - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_3
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_3
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_3
-    - path::./:
-        title: Step Test - default alias with APK signer
-        inputs:
-        - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_3_URL
-        - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_3
-        - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_3
-        - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_3
-        - use_apk_signer: true
+        - use_apk_signer: $APK_SIGNER
+
+  test4:
+    steps:
     - path::./:
         title: Step Test - android studio generated keystore (jks)
         inputs:
@@ -156,14 +214,10 @@ workflows:
         - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
-    - path::./:
-        title: Step Test - android studio generated keystore (jks) with APK signer
-        inputs:
-        - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_4_URL
-        - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4
-        - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
-        - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
-        - use_apk_signer: true
+        - use_apk_signer: $APK_SIGNER
+
+  test5:
+    steps:
     - path::./:
         title: Step Test - android studio generated keystore (jks) + custom artifact name
         inputs:
@@ -172,15 +226,10 @@ workflows:
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
         - output_name: "test-artifact-name"
-    - path::./:
-        title: Step Test - android studio generated keystore (jks) + custom artifact name with APK signer
-        inputs:
-        - keystore_url: $BITRISEIO_ANDROID_KEYSTORE_4_URL
-        - keystore_password: $BITRISEIO_ANDROID_KEYSTORE_PASSWORD_4
-        - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
-        - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
-        - output_name: "test-artifact-name"
-        - use_apk_signer: true
+        - use_apk_signer: $APK_SIGNER
+
+  test6:
+    steps:
     - path::./:
         title: Step Test - android studio generated keystore (jks) + custom artifact name second time to see collisions if any
         inputs:
@@ -189,6 +238,7 @@ workflows:
         - keystore_alias: $BITRISEIO_ANDROID_KEYSTORE_ALIAS_4
         - private_key_password: $BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD_4
         - output_name: "test-artifact-name"
+        - use_apk_signer: $APK_SIGNER
 
   _go_tests:
     steps:
@@ -209,7 +259,7 @@ workflows:
         title: Dependency update
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
             go get -u -v github.com/golang/dep/cmd/dep
             dep ensure -v
@@ -222,6 +272,6 @@ workflows:
     - script:
         inputs:
         - content: |-
-            #!/bin/bash
+            #!/usr/bin/env bash
             set -ex
             stepman audit --step-yml ./step.yml
